### ISSUE TITLE
Star Catalog, ship accell/decell profiles?

### ISSUE THREAD

**Issue by iontom** [dvolk/27kelvin#1]
Hey! I've been thinking about a project like this! This is amazing!

I was actually looking at various star catalogs out there trying to to get an appropriate XYZ offset from Sol with respect to the galactic plane. I found a few from Project Rho but learned that his transformations were very wrong.

If I were to prep a list of stars in XYZ for you (plus star type, age, etc), could you refactor something to read csv or JSON? Everything within 50 LY would be pretty cool.

The next step would be realistic planet type formation rates, informed by data from Kepler and other surveys. Hint: there's a LOT of ocean and ice planets out there.

**Comment by dvolk** [comment]
Thank you for your interest. Unfortunately, this repo is provided as-is. Bringing it into a playable state would require significant work (probably a rewrite) that that I don't have time to commit right now.

**Comment by iontom** [comment]
Understood. I'm insanely swamped these days too. If you ever decide to put a license on this maybe I'll do a pull request on it in a few months.

Cheers!

**Comment by dvolk** [comment]
Oh right, no problem. License added.
